name: TNTModifier
version: 1.1.0
main: me.thevipershow.tntmodifier.TNTModifier
authors: [TheViperShow]
description: Modify TNT mechanics.
commands:
  tnt-modifier:
    aliases: [tntmodifier, tntm]
    description: "TNTModifier's main command."
    permission: tntmodifier.admin
    permission-message: "§8[cTNTModifier§8]§7: You don't have permissions to do this."
